# Generated by Django 3.2 on 2021-04-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '0005_auto_20210409_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('chat_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта')),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_manager.student')),
            ],
            options={
                'verbose_name': 'Телеграм пользователя',
                'verbose_name_plural': 'Телеграм пользователь',
            },
        ),
    ]
