# Generated by Django 3.2 on 2021-04-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студента', 'verbose_name_plural': 'Студент'},
        ),
    ]
