# Generated by Django 3.2 on 2021-04-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
