# Generated by Django 3.2 on 2021-04-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_auto_20210409_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, verbose_name='Токен')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использовано')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='authorization_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.authorizationtoken', verbose_name='Токен авторизации'),
        ),
    ]
