# Generated by Django 3.2 on 2021-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_auto_20210409_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сложность'),
        ),
    ]
