# Generated by Django 3.2 on 2021-04-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_project_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sent_out',
            field=models.BooleanField(default=False, verbose_name='Разослали'),
        ),
    ]
